### ISSUE TITLE
Would you mind guiding me on how to implement your method for a remote eye tracker?

### ISSUE THREAD

**Issue by DoPhu97** [gkaguirrelab/transparentTrack#158]
Dear Prof. G. K. Aguirre,

My name is Phu Do-Tuong. I received the M.S. degree in Engineering Physics from Ho Chi Minh City University of Technology in Vietnam in 2021, and after that, I completed my military service in January of this year.

Thank you for sharing this fantastic open-source work. I am really interested in the result that the image-plane translation of the head was estimated with sub-millimeter accuracy.

I would like to measure the radius of children’s pupils and corneas. Because my subjects are children, I tend to build a remote eye tracker. I guess that we might use a more complex configuration (more light sources and/or more cameras). Would you mind guiding me on how to implement your method for a remote eye tracker?

Student name,
Phu Do-Tuong

**Comment by gkaguirre** [comment]
Hello Phu. As a general matter, the code has two major components:

First, `gkaModelEye` is a "forward model" that creates an 2D image of the appearance of the eye as seen by a camera. The parameters of the model include biometric properties of the eye, active properties of the eye "pose" (rotation, translation, and pupil size), and geometric properties of the initial position of the camera (including relative camera position and number and position of active IR light sources). Your first task is to set up the parameters of the model so that the biometric and geometric properties of the recording are accurately captured. You can compare the rendered output of the model to the images that your camera records to see if you can get these to match.

Second, given the biometric and geometric parameters (the "scene"), you can then use `transparentTrack` to search for eye pose values (rotation, translation, pupil size) that produce an image that match the glints and pupil boundary seen in a particular frame of an eye tracking video. The transparent track routines try to find the pupil boundary and IR glints, and then do this fitting. Essentially, transparentTrack is a big wrapper around the `gkaModelEye` function `eyePoseEllipseFit.m`, which attempts to find the eye pose (given the scene geometry) that best accounts for the pupil perimeter and glint.

These days, there are better (CNN based) software solutions out there for finding the pupil boundary, so you could also use that. 

Hope that helps.

**Comment by DoPhu97** [comment]
Hello Prof. G. K. Aguirre,
Thank you for your detailed answer. I will implement your instructtions.
